[package]
name = "hashtest"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.twox-hash]
version = "1.6.3"
default-features = false
# features = ["std"]

